---
galaxy_info:
  role_name: cmkAgentRegistration
  author: Alfred TCHONDJO
  description: Register Host at checkMK site, discover services and activate these changes
  company: Iriven Group

  license: GPLv2

  min_ansible_version: 2.9

dependencies:
  - cmkAgentInstaller
  - cmkConnectionAttributes
