---
- name: PREPARE CRONTAB MANDATORIES PARAMS
  block:
    - name: Ensure Vault Secret file exists.
      ansible.builtin.lineinfile:
        path: "{{ vaultPasswdFile }}"
        state: present
        line: "{{ vaultPasswd }}"
        owner: root
        group: root
        mode: '0644'
        create: yes
      delegate_to: localhost

    - name: Get Agent predicitive registration date
      ansible.builtin.shell: |
        set timeout 10
        date -d '25hour30min' +'%m-%d-%H-%M'
      register: AgentRegistrationDate
      failed_when: AgentRegistrationDate.rc > 0
      delegate_to: localhost

    - name: Parse previous result to retrieve scheduler Parameters
      ansible.builtin.set_fact:
        regMonth:   "{{ AgentRegistrationDate.stdout.split('-') | first }}"
        regDay:     "{{ AgentRegistrationDate.stdout.split('-')[1] }}"
        regHour:    "{{ AgentRegistrationDate.stdout.split('-')[2] }}"
        regMin:     "{{ AgentRegistrationDate.stdout.split('-') | last }}"
      when: AgentRegistrationDate is defined and AgentRegistrationDate.rc == 0

    - name: Scheduling CheckMK Agent registration
      ansible.builtin.cron:
        name: CheckMK Agent AutoDeploy
        month:    "{{ regMonth|int }}"
        day:      "{{ regDay|int }}"
        hour:     "{{ regHour|int }}"
        minute:   "{{ regMin|int }}"
        user:     root
        job: "ansible-playbook -i {{inventory_hostname_short|lower}}, {{playbook_dir}}/cmkAgent_Deployment.yml --vault-password-file {{ vaultPasswdFile }} >> /var/log/cmkAgentAutoRegistration.log"
        cron_file: ansible_checkMK-agent-autoInstall-{{ inventory_hostname_short|lower }}
      become: true
      delegate_to: localhost
      when:
        - regMonth is defined and regMonth|int > 0
        - regDay   is defined and regDay|int > 0
        - regHour  is defined and regHour|int >= 0
        - regMin   is defined and regMin|int  >= 0
      vars:
        - log_path: /var/log/cmkAgentAutoRegistration.log

  when:
    - dburl is defined and dburl|length >0
    - dbtoken is defined and dbtoken|length >0
    - vaultPasswdFile is defined and vaultPasswdFile|length >0
    - vaultPasswd is defined and vaultPasswd|length >0
