---
- name: CHECKMK AGENT DECOMMISSION
  block:
    - name: Remove host from Checkmk monitoring system
      local_action:
        module: uri
        url: "{{ cmkAgent.config.apiurl }}/objects/host_config/{{ cmkAgent.hostname|lower }}"
        method: DELETE
        headers:
          Content-Type: application/json
          Accept: application/json
          Authorization: "Bearer {{ cmkAgent.config.apiuser }} {{ cmkAgent.config.apikey }}"
      register: DecommResponse
      failed_when: (DecommResponse.status not in [200, 204])
      changed_when: DecommResponse.status == 204

    - name: Activating all pending changes
      local_action:
        module: uri
        url:  "{{ cmkAgent.config.apiurl }}/domain-types/activation_run/actions/activate-changes/invoke"
        method: POST
        headers:
          Content-Type: application/json
          Accept: application/json
          If-Match: "*"
          Authorization: "Bearer {{ cmkAgent.config.apiuser }} {{ cmkAgent.config.apikey }}"
        body_format: json
        body:
          redirect: "false"
          sites:
            - "{{ cmkconnections.activelink.site|lower }}"
          force_foreign_changes: "true"
      register: activationResponse
      failed_when: activationResponse.status >= 400 and activationResponse.status != 422
      run_once: 'true'
      when:
        - DecommResponse is defined and DecommResponse.status < 400

  when:
    - dburl is defined and dburl|length >0
    - dbtoken is defined and dbtoken|length >0
    - DBQuery is defined and DBQuery.status < 400 and DBQuery.json|length >0
    - cmkAgent is defined and cmkAgent.config|length > 0
    - cmkconnections is defined and cmkconnections.activelink|length > 0
