---
- name: DEPLOYING ON DEBIAN FAMILY SERVERS
  block:
    - name: Download Debian derivatives agents shipped with Checkmk from central site
      local_action:
        module: get_url
        url: "{{ cmkAgent.config.apiurl }}/domain-types/agent/actions/download/invoke?os_type=linux_deb"
        dest: /tmp/cmkAgent.deb
        force: true
        headers:
          Authorization: "Bearer {{ cmkAgent.config.apiuser }} {{ cmkAgent.config.apikey }}"
          Accept: "application/octet-stream"

    - name: Uploading Debian derivatives package to current host
      ansible.builtin.copy:
        src: /tmp/cmkAgent.deb
        dest: /tmp/
        mode: u+rw,g-wx,o-wx

    - name: Installing Checkmk Monitoring Agent (Debian, derivatives).
      become: true
      ansible.builtin.apt:
        deb: /tmp/cmkAgent.deb
        state: present
        update_cache: yes

  when: ansible_os_family == 'Debian'

- name: DEPLOYING ON REDHAT FAMILY SERVERS
  block:
    - name: Download Redhat derivatives agents shipped with Checkmk from central site
      local_action:
        module: get_url
        url: "{{ cmkAgent.config.apiurl }}/domain-types/agent/actions/download/invoke?os_type=linux_rpm"
        dest: /tmp/cmkAgent.rpm
        force: true
        headers:
          Authorization: "Bearer {{ cmkAgent.config.apiuser }} {{ cmkAgent.config.apikey }}"
          Accept: "application/octet-stream"

    - name: Uploading  Redhat derivatives package to current host
      ansible.builtin.copy:
        src: /tmp/cmkAgent.rpm
        dest: /tmp/
        mode: u+rw,g-wx,o-wx

    - name: Installing Checkmk Monitoring Agent (Red Hat 7, derivatives, and earlier).
      become: true
      ansible.builtin.yum:
        name: /tmp/cmkAgent.rpm
        state: latest
        update_cache: yes
      when:
        - ansible_pkg_mgr == 'yum'
      vars:
        ansible_python_interpreter: auto_silent

    - name: Installing Checkmk Monitoring Agent (Red Hat 8, derivatives, and later).
      become: true
      ansible.builtin.dnf:
        name: /tmp/cmkAgent.rpm
        state: latest
        update_cache: yes
        disable_gpg_check: True
      when:
        - ansible_pkg_mgr == 'dnf'
      vars:
        ansible_python_interpreter: auto_silent
        
  when: ansible_os_family == 'RedHat'

- name: SERVICES CONFIGURATION
  block:
    - name: Configuring services of new installed agent
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/check_mk/
        owner: root
        group: root
        mode: u+rwx,g-wx,o-wx
        force: yes
      register: configservices
      with_fileglob:
        - services/*.cfg



---
# - name: DEPLOY MANDATORIES DEPENDENCIES ON AGENT
#   block:
#     - name: Installing Debsums runtime dependency on Agent (Debian, derivatives).
#       become: true
#       ansible.builtin.apt:
#         name: debsums
#         state: present
#         update_cache: yes
#         autoremove: yes
#         purge: true
#   when: ansible_os_family == 'Debian'

# - name: DEPLOYING LOCAL MODULES ON AGENT
#   block:
#     - name: Deploy checkmk Custom scripts on current Agent
#       ansible.builtin.copy:
#         src: "{{ item }}"
#         dest: /usr/lib/check_mk_agent/local
#         owner: root
#         group: root
#         mode: 0755
#       register: fileDeployment
#       with_fileglob:
#         - modules/common/*
#         - modules/{{ansible_os_family|lower}}/*

#     - name: Normalizing EOL for new uploaded files
#       ansible.builtin.shell: dos2unix $(find /usr/lib/check_mk_agent/local -type f)
#       when: fileDeployment.changed|bool


# - name: REGISTER CHANGES ON CHEKMK SERVER
#   block:
#     - name: Execute a service discovery from Checkmk server
#       local_action:
#         module: uri
#         url: "{{ cmkAgent.config.apiurl }}/domain-types/service_discovery_run/actions/start/invoke"
#         method: POST
#         headers:
#           Content-Type: application/json
#           Accept: application/json
#           Authorization: "Bearer {{ cmkAgent.config.apiuser }} {{ cmkAgent.config.apikey }}"
#         body_format: json
#         body:
#           host_name: "{{ cmkAgent.hostname }}"
#           mode: "fix_all"
#       register: AcceptedResponse
#       failed_when: AcceptedResponse.status >= 400
#       when:
#         - fileDeployment.changed|bool

#     - name: Activating all pending changes
#       local_action:
#         module: uri
#         url:  "{{ cmkAgent.config.apiurl }}/domain-types/activation_run/actions/activate-changes/invoke"
#         method: POST
#         headers:
#           Content-Type: application/json
#           Accept: application/json
#           If-Match: "*"
#           Authorization: "Bearer {{ cmkAgent.config.apiuser }} {{ cmkAgent.config.apikey }}"
#         body_format: json
#         body:
#           redirect: "false"
#           sites:
#             - "{{ cmkAgent.config.remotesite|lower }}"
#           force_foreign_changes: "false"
#       register: activateModuleResponse
#       run_once: 'true'
#       failed_when: activateModuleResponse.status >= 400 and activateModuleResponse.status != 422
#       when:
#         - fileDeployment.changed|bool
#         - AcceptedResponse.status  < 400
