---
- name: DEPLOYING ON DEBIAN FAMILY SERVERS
  block:
    - name: Download Debian derivatives agents shipped with Checkmk from central site
      local_action:
        module: get_url
        url: "{{ cmkAgent.config.apiurl }}/domain-types/agent/actions/download/invoke?os_type=linux_deb"
        dest: /tmp/cmkAgent.deb
        force: true
        headers:
          Authorization: "Bearer {{ cmkAgent.config.apiuser }} {{ cmkAgent.config.apikey }}"
          Accept: "application/octet-stream"

    - name: Uploading Debian derivatives package to current host
      ansible.builtin.copy:
        src: /tmp/cmkAgent.deb
        dest: /tmp/
        mode: u+rw,g-wx,o-wx

    - name: Installing Checkmk Monitoring Agent (Debian, derivatives).
      become: true
      ansible.builtin.apt:
        deb: /tmp/cmkAgent.deb
        state: present
        update_cache: yes

  when: ansible_os_family == 'Debian'

- name: DEPLOYING ON REDHAT FAMILY SERVERS
  block:
    - name: Download Redhat derivatives agents shipped with Checkmk from central site
      local_action:
        module: get_url
        url: "{{ cmkAgent.config.apiurl }}/domain-types/agent/actions/download/invoke?os_type=linux_rpm"
        dest: /tmp/cmkAgent.rpm
        force: true
        headers:
          Authorization: "Bearer {{ cmkAgent.config.apiuser }} {{ cmkAgent.config.apikey }}"
          Accept: "application/octet-stream"

    - name: Uploading  Redhat derivatives package to current host
      ansible.builtin.copy:
        src: /tmp/cmkAgent.rpm
        dest: /tmp/
        mode: u+rw,g-wx,o-wx

    - name: Installing Checkmk Monitoring Agent (Red Hat 7, derivatives, and earlier).
      become: true
      ansible.builtin.yum:
        name: /tmp/cmkAgent.rpm
        state: latest
        update_cache: yes
      when:
        - ansible_pkg_mgr == 'yum'
      vars:
        ansible_python_interpreter: auto_silent

    - name: Installing Checkmk Monitoring Agent (Red Hat 8, derivatives, and later).
      become: true
      ansible.builtin.dnf:
        name: /tmp/cmkAgent.rpm
        state: latest
        update_cache: yes
        disable_gpg_check: True
      when:
        - ansible_pkg_mgr == 'dnf'
      vars:
        ansible_python_interpreter: auto_silent
        
  when: ansible_os_family == 'RedHat'

- name: SERVICES CONFIGURATION
  block:
    - name: Configuring services of new installed agent
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/check_mk/
        owner: root
        group: root
        mode: u+rwx,g-wx,o-wx
        force: yes
      register: configservices
      with_fileglob:
        - services/*.cfg
